# Generated by Django 3.1.1 on 2021-04-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210413_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='test_code',
            field=models.TextField(default='print("Hello World!")'),
        ),
    ]
