# Generated by Django 3.1.1 on 2021-04-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210413_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test_code',
        ),
    ]
