# Generated by Django 3.1.1 on 2021-04-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_test_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_code',
            field=models.TextField(default='print("Hello World!")'),
        ),
    ]
