# Generated by Django 3.1.7 on 2021-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='approach',
            field=models.TextField(default=''),
        ),
    ]
