# Generated by Django 3.1.7 on 2021-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_auto_20210317_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='points',
            field=models.IntegerField(default=3),
        ),
    ]
