# Generated by Django 3.1.7 on 2021-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_remove_topic_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='approach',
            field=models.TextField(default='print("Hello World!")'),
        ),
    ]
