# Generated by Django 3.1.1 on 2021-04-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0015_auto_20210327_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='approach',
        ),
    ]
