# Generated by Django 3.1.1 on 2021-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0016_remove_topic_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='approach',
            field=models.TextField(default='print("Hello World!")'),
        ),
        migrations.AlterField(
            model_name='userapproach',
            name='user_approach',
            field=models.TextField(default=''),
        ),
    ]
