# Generated by Django 3.1.1 on 2022-02-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_test_code'),
        ('users', '0005_auto_20210413_0912'),
    ]

    operations = [
    ]
