# Generated by Django 3.1.1 on 2022-04-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Ustawienia profilu'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
    ]
