# Generated by Django 3.1.7 on 2021-03-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_auto_20210327_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='output',
            field=models.TextField(default='Hello World!'),
        ),
    ]
