# Generated by Django 3.1.7 on 2021-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0014_auto_20210327_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapproach',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userapproach',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
