# Generated by Django 3.1.1 on 2021-04-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0018_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
