# Generated by Django 3.1.1 on 2022-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0020_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='code_text',
            field=models.TextField(default=''),
        ),
    ]
