# Generated by Django 3.2.13 on 2022-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0022_auto_20220206_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pomoc_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
